---
- name: mkdir ~/bin 
  become: true
  become_user: "{{username}}"
  file: 
   path: ~/bin
   state: directory
   recurse: yes
   owner: "{{username}}"
   group: "{{username}}"


- name: Download http://commondatastorage.googleapis.com/git-repo-downloads/repo
  become: true
  become_user: "{{username}}"
  get_url:
    url: http://commondatastorage.googleapis.com/git-repo-downloads/repo
    dest: ~/bin/repo

- name: Changing perm of "~/bin/repo", adding "+x"
  become: true
  become_user: "{{username}}"
  file: dest=~/bin/repo mode=a+x    


- name: Change file ownership, group and permissions
  file:
    path: "{{build_directory}}"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: '0700'



- name: Create $PATH
  become: true
  become_user: "{{username}}"
  shell: PATH=~/bin:$PATH 


- name: replace '#!/usr/bin/env python$' replace='#!/usr/bin/env python2' 
  become: true
  become_user: "{{username}}"
  replace: path=~/bin/repo regexp='#!/usr/bin/env python$' replace='#!/usr/bin/env python2'



- name: yum install centos-release-scl-2-3.el7.centos.noarch.rpm 
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm
    state: present


- name: yum install centos-release-scl-2-3.el7.centos.noarch.rpm 
  yum:
    name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm
    state: present


- name: yum -y --enablerepo=centos-sclo-rh
  yum_repository:
    name: centos-sclo-rh
    description: centos-sclo-rh
    baseurl: http://mirrorlist.centos.org?arch=$basearch&release=7&repo=sclo-rh
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo


- name: install devtoolset-7 devtoolset-7-libatomic-devel
  yum: 
    name: "{{ packages }}"
  vars:
    packages:
    - devtoolset-7 
    - devtoolset-7-libatomic-devel

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no


- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: sicom*
    state: absent
  notify: yum-clean-metadata


- name: install devtoolset-7 devtoolset-7-libatomic-devel
  yum: 
    name: "{{ packages }}"
  vars:
    packages:
    - centos-release-scl
