---

- name: yum-fail2ban
  yum: name=fail2ban state=present disable_gpg_check=yes

- name: fail2ban witelist
  lineinfile: path=/etc/fail2ban/jail.conf regexp='^ignoreip = 127.0.0.1/8' line='ignoreip = 127.0.0.1/8 217.24.175.175 217.20.178.185 91.215.55.5'

- name: Put fail2ban jail.local config
  template: src=templates/fail2ban_jail.local.j2 dest="/etc/fail2ban/jail.local"

- name: Move fail2ban firewalld.conf
  copy: remote_src=True src="/etc/fail2ban/jail.d/00-firewalld.conf" dest="/etc/fail2ban/jail.d/00-firewalld.conf.backup"
  ignore_errors: yes

- name: Delete fail2ban firewalld.conf
  file: path="/etc/fail2ban/jail.d/00-firewalld.conf" state=absent

- name: Ensure that fail2ban started
  service: name=fail2ban enabled=yes state=started

- name: fail2ban restart
  shell: service fail2ban restart

