---

- name: Setup default git configuraiton
  become: Yes
  become_user: "{{username}}"
  git_config:
       name="{{ item.name }}"
    scope=global
    value="{{ item.value }}" 
  with_items:
    - {name: "user.name",  value: "{{git_name}}" }
    - {name: "user.email", value: "{{git_email}}" }
    - {name: "ui.color",   value: "True" }

- name: create config file
  become: Yes
  become_user: "{{username}}"
  file: path=~/.ssh/config state=touch 

- name: Insert/Update 
  become: Yes
  become_user: "{{username}}"
  blockinfile:
    path: ~/.ssh/config
    block: |
      host=*  
      StrictHostKeyChecking no
      port=7999
    state: present

    
- name: repo init -u ssh://git@stash.sicom.com:7999/system/sicom-manifest.git -b sicom-v2018.10-sumo-pos
  become: Yes
  become_user: "{{username}}"
  shell: cd "{{build_directory}}";  ~/bin/repo init -u ssh://git@stash.sicom.com:7999/system/sicom-manifest.git -b sicom-v2018.10-sumo-pos

- name: repo sync
  become: Yes
  become_user: "{{username}}"
  shell: cd "{{build_directory}}";  ~/bin/repo sync
