---

- name: Setup default git configuraiton
  become: Yes
  become_user: provision
  git_config:
       name="{{ item.name }}"
    scope=global
    value="{{ item.value }}" 
  with_items:
    - {name: "user.name",  value: "Serhii Polovyi" }
    - {name: "user.email", value: "spolovyi@xenial.org" }
    - {name: "ui.color",   value: "True" }

- name: create config file
  become: Yes
  become_user: provision
  file: path=~/.ssh/config state=touch 

- name: Insert/Update 
  become: Yes
  become_user: provision
  blockinfile:
    path: ~/.ssh/config
    block: |
      host=*  
      StrictHostKeyChecking no
      port=7999
    state: present

    
- name: repo init -u ssh://git@stash.sicom.com:7999/system/sicom-manifest.git -b sicom-v2018.10-sumo-pos
  become: Yes
  become_user: provision
  shell: cd /sicom3;  ~/bin/repo init -u ssh://git@stash.sicom.com:7999/system/sicom-manifest.git -b sicom-v2018.10-sumo-pos

- name: repo sync
  become: Yes
  become_user: provision
  shell: cd /sicom3;  ~/bin/repo sync
