---

- name: remove extraneous hosts entries
  copy:
  dest: /etc/hosts
  content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
- name: turn selinux off
  selinux: policy=targeted state=permissive
