---

- name: /etc/hosts
  blockinfile: 
    dest: /etc/hosts
    block: |
      10.20.40.192 stash.sicom.com
      52.2.214.187 git.linaro.org
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      #  delegate_to: localhost
  

- name: turn selinux off
  selinux: policy=targeted state=permissive




- name: configure aggregates of static routes
  shell: ip route add 10.20.40.192 via 10.110.10.102 ; ip route add 52.2.214.187 via 10.110.10.102 
  ignore_errors: yes




        #- name: configure static route
        #  net_static_route#:
        #    prefix: 10.20.40.192
        #    mask: 255.255.255.255
        #    next_hop: 10.110.10.102

        #- name: configure static route
        #  net_static_route:
        #    prefix: 52.2.214.187
        #    mask: 255.255.255.255
        #    next_hop: 10.110.10.102
