---

# - include_tasks: hostname.yml
 - include_tasks: useradd.yml
 - include_tasks: yum.yml
 - include_tasks: create_path.yml
 - include_tasks: selinux.yml
 - include_tasks: gitconfig.yml
 - include_tasks: patch.yml
 - include_tasks: run_build.yml
#  - include_tasks: timezone.yml
#  - include_tasks: xen_addons.yml
#  - include_tasks: fail2ban.yml
#    when: fail2ban_install == "true"
# - include_tasks: tuned_system.yml
