---


- name: create reppo mongo3.6
  copy: src="files/mongodb-org-3.6.repo" dest="/etc/yum.repos.d/mongodb-org-3.6.repo"

- name: yum install mongo 3.6
  yum: pkg={{item}} state=present disable_gpg_check=yes
  with_items:
  - mongodb-org

- name: Put /etc/mongod.conf
  template: src=templates/mongod.conf.j2 dest=/etc/mongod.conf mode=0644

- name: Put backup script to /usr/bin/mongobackup path
  template: src=templates/mongobackup.sh.j2 dest=/usr/bin/mongobackup mode=0755

- name: Put backup script disable-transparent-hugepages
  template: src=templates/disable-transparent-hugepages.j2 dest=/etc/init.d/disable-transparent-hugepages mode=0755

- name: Ensure that disable-transparent-hugepages started
  service: name=disable-transparent-hugepages enabled=yes state=started

- name: Ensure that Mongod started
  service: name=mongod enabled=yes state=started

- name: Add daily backup tasks to cron
  cron: user=root name="Backup Mongo DB daily" minute="30" hour="2" job="mongobackup {{backup_client_name}} store" state=present

- name: Add rotate mongo log tasks to cron
  cron: user=root name="rotate mongo log" minute="0" hour="0" day="1" job="pkill -SIGUSR1 mongod" state=present

