---

#- name: add support user
#  user: name=support shell=/bin/bash append=yes

- name: tuned off
  service: name=tuned state=stopped enabled=no
  ignore_errors: yes

- name: upgrade all packages
  yum: name='*' state=latest

- name: /etc/security/limits.conf  max open files 131072
  lineinfile: path=/etc/security/limits.conf line='*               soft    nofile          131072'

- name: /etc/security/limits.conf  max user processes 131072
  lineinfile: path=/etc/security/limits.conf line='*               hard    nofile          131072'

- name: /etc/security/limits.conf  max open files 131072
  lineinfile: path=/etc/security/limits.conf line='*               soft    nproc           131072'

- name: /etc/security/limits.conf  max user processes 131072
  lineinfile: path=/etc/security/limits.conf line='*               hard    nproc           131072'


- name: reboot server
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_server == "yes"

- name: reboot pause 20 seconds
  pause: seconds=20
  when: reboot_server == "yes"

- name: wait server after reboot 
  local_action: wait_for host={{inventory_hostname}} port={{ssh_port}} state=started timeout=300
  when: reboot_server == "yes"

- name: uptime
  shell: "uptime"
  register: result

- name: uptime msg
  debug: msg={{result.stdout}}

