---
#- hosts: all
#  vars:
#    - provision_password: '$6$w9S3t7x1kRtmG0u$6nVU9KZsC12Q8DYI4FtgKPy.e/cq/jseB/.DViTO1SpUnoCy.dxcOf8hyfitGq5V0yhgXccxzlqm2o.I3SlDJ0'
#  remote_user: root
 
 
  - name: Add a new user named provision
    user:
         name=provision
         password="F7jde(Fr8r3kfr484vfje@#$458jF%(ff"
 
  - name: Add provision user to the sudoers
    copy:
         dest: "/etc/sudoers.d/provision"
         content: "provision  ALL=(ALL)  ALL"
  - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
    user:
         name: provision
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa i



  - name: cat ~/.ssh/id_rda.pub
    become: true
    become_user: provision
    script: cat ~/.ssh/id_rda.pub
    register: out

  - debug: var=out.stdout_lines
