---
 
  - name: Add a new user named {{username}}
    user:
         name: "{{username}}"
 #         password: "{{password}}"
 
  - name: Add {{username}} user to the sudoers
    copy:
         dest: "/etc/sudoers.d/{{username}}"
         content: "{{username}}  ALL=(ALL)  ALL"


  - name: Create a 2048-bit SSH key for user {{username}} ~/.ssh/id_rsa
    user:
         name: "{{username}}"
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/id_rsa 



  - name: cat ~/.ssh/id_rda.pub
    become: true
    become_user: "{{username}}"
    shell: cat ~/.ssh/id_rsa.pub
    register: out

  - debug: var=out.stdout_lines
