---


- name: yum reppo zabbix
#  yum: name=http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm state=present disable_gpg_check=yes
  yum: name=https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm state=present disable_gpg_check=yes


- name: yum install zabbix-agent
  yum: name=zabbix-agent state=present disable_gpg_check=yes

- name: yum install zabbix-sender
  yum: name=zabbix-sender state=present disable_gpg_check=yes

- name: yum install python-pyzabbix
  yum: name=python-pyzabbix state=present disable_gpg_check=yes

#- name: postgres
#  yum: name=http://cdn.cavaliercoder.com/libzbxpgsql/yum/zabbix30/rhel/7/x86_64/libzbxpgsql-1.1.0-1.el7.x86_64.rpm state=present disable_gpg_check=yes
#  when: postgres_server == "true"

- name: Create directory /etc/zabbix/scripts
  file: path="/etc/zabbix/scripts" state=directory

- name: Put zabbix_postgresql.py for zabbix
  copy: src=templates/zabbix/zabbix_postgresql.py.j2 dest="/etc/zabbix/scripts/zabbix_postgresql.py" mode=0755

- name: Put postgres.conf.j2 for zabbix
  copy: src=templates/zabbix/postgres.conf.j2 dest="/etc/zabbix/zabbix_agentd.d/postgres.conf"
  when: postgres_server == "true"

- name: Put zabbix_mongodb.py for zabbix
  copy: src=templates/zabbix/zabbix_mongodb.py.j2 dest="/etc/zabbix/scripts/zabbix_mongodb.py" mode=0755

- name: Put zabbix_hdd.py for zabbix
  copy: src=templates/zabbix/zabbix_hdd.py.j2 dest="/etc/zabbix/scripts/zabbix_hdd.py" mode=0755

- name: Put mongo.conf.j2 for zabbix
  copy: src=templates/zabbix/mongo.conf.j2 dest="/etc/zabbix/zabbix_agentd.d/mongo.conf"
  when: mongo_server == "true"

- name: Put iostat-collect.sh for zabbix
  copy: src=templates/zabbix/iostat-collect.sh.j2 dest="/etc/zabbix/scripts/iostat-collect.sh" mode=0755

- name: Put iostat-parse.sh for zabbix
  copy: src=templates/zabbix/iostat-parse.sh.j2 dest="/etc/zabbix/scripts/iostat-parse.sh" mode=0755

- name: Copy userparameter.conf
  copy: src=templates/zabbix/userparameter.conf.j2 dest="/etc/zabbix/zabbix_agentd.d/userparameter.conf"



#- name: Put userparameter.conf for zabbix
#  template: src=templates/zabbix/userparameter.conf.j2 dest="/etc/zabbix/zabbix_agentd.d/userparameter.conf"

- name: /etc/zabbix/zabbix_agentd.conf Server
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^Server=127.0.0.1' replace='Server={{zabbix_server}}'

- name: /etc/zabbix/zabbix_agentd.conf ServerActive
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^ServerActive=127.0.0.1' replace='ServerActive={{zabbix_server}}'

- name: /etc/zabbix/zabbix_agentd.conf Hostname
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^Hostname=Zabbix server' replace='Hostname={{zabbix_host_name}}'

- name: /etc/zabbix/zabbix_agentd.conf Timeout
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^# Timeout=3' replace='Timeout=30'

- name: /etc/zabbix/zabbix_agentd.conf AllowRoot
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^# AllowRoot=0' replace='AllowRoot=1'

- name: /etc/zabbix/zabbix_agentd.conf UnsafeUserParameters
  replace: path=/etc/zabbix/zabbix_agentd.conf regexp='^# UnsafeUserParameters=0' replace='UnsafeUserParameters=1'


- name: Ensure that zabbix-agent started
  service: name=zabbix-agent enabled=yes state=started

