name: MasterCI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: touch /tmp/123
      - run: ls -lah /tmp/123
      - run: pwd
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: /tmp/*
          host: 178.150.65.210
          remote: /home2
          user: root
          key: ${{ secrets.SSH_KEY }}
